# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_b_inbr_bed_cpp <- function(file, m_loci, n_ind, mean_kinship, indexes_ind_R) {
    .Call('_ligera_get_b_inbr_bed_cpp', PACKAGE = 'ligera', file, m_loci, n_ind, mean_kinship, indexes_ind_R)
}

